SEP_ARTICLES = {
    "Logic & Argumentation": [
        "logic-classical",
        "logic-informal",
        "logic-inductive",
        "logic-relevance",
        "logic-temporal",
        "logic-paraconsistent",
        "logic-intuitionistic",
        "logic-fuzzy",
        "logic-modal",
        "logic-connexive",
        "dynamic-epistemic",
        "logic-linear",
        "proof-theory",
        "type-theory",
        "abduction",
        "argument",
        "reasoning-analogy",
        "fallacies",
        "conditionals",
        "contradiction",
        "dialetheism",
        "liar-paradox",
        "curry-paradox",
        "russell-paradox",
        "sorites-paradox",
        "paradox-zeno",
        "qt-quantlog",
        "logical-consequence",
        "logical-truth",
        "logical-constants",
        "diagrams",
    ],

    "Epistemology": [
        "epistemology",
        "epistemology-social",
        "epistemology-bayesian",
        "knowledge-analysis",
        "skepticism",
        "justification-intext",
        "reliabilism",
        "evidence",
        "rationalism-empiricism",
        "relativism",
        "disagreement",
    ],

    "Ethics": [
        "ethics-virtue",
        "consequentialism",
        "ethics-deontological",
        "metaethics",
        "moral-realism",
        "moral-anti-realism",
        "moral-relativism",
        "moral-dilemmas",
        "moral-responsibility",
        "utilitarianism-history",
        "abortion",
        "euthanasia-voluntary",
        "rights-human",
        "moral-animal",
        "well-being",
    ],

    "Political Philosophy": [
        "democracy",
        "liberalism",
        "libertarianism",
        "socialism",
        "anarchism",
        "authority",
        "civil-disobedience",
        "freedom-speech",
        "privacy",
        "pornography-censorship",
        "property",
        "contractarianism",
        "equality",
        "immigration",
        "nationalism",
        "justice",
        "legitimacy",
        "multiculturalism",
    ],

    "Metaphysics": [
        "metaphysics",
        "identity-personal",
        "causation-metaphysics",
        "determinism-causal",
        "freewill",
        "time",
    ],

    "Philosophy of Mind": [
        "consciousness",
        "intentionality",
        "dualism",
        "physicalism",
        "functionalism",
        "artificial-intelligence",
        "chinese-room",
        "turing-test",
        "belief",
        "emotion",
        "panpsychism",
    ],

    "Philosophy of Science": [
        "scientific-method",
        "scientific-realism",
        "pseudo-science",
        "scientific-explanation",
        "scientific-progress",
        "scientific-objectivity",
        "confirmation",
        "evolution",
        "natural-selection",
    ],

    "History of Western Philosophy": [
        "plato",
        "aristotle",
        "socrates",
        "stoicism",
        "descartes",
        "locke",
        "hume",
        "kant",
        "nietzsche",
        "marx",
    ],

    "20th-21st Century Philosophy": [
        "phenomenology",
        "existentialism",
        "postmodernism",
        "foucault",
        "rawls",
        "critical-theory",
        "feminism-approaches",
    ],

    "Philosophy of Law": [
        "legal-positivism",
        "natural-law-theories",
        "legal-rights",
        "legal-punishment",
        "constitutionalism",
        "rule-of-law",
    ],

    "Applied & Emerging": [
        "ethics-ai",
        "enhancement",
        "neuroethics",
        "race",
        "disability",
        "justice-inequality-health",
        "ethics-social-networking",
        "hate-speech",
        "affirmative-action",
        "justice-climate",
        "feminist-philosophy",
        "feminist-social-epistemology",
        "critical-philosophy-race",
        "dehumanization",
        "exploitation",
        "privacy-medicine",
        "informed-consent",
        "stem-cells",
        "cloning",
        "eugenics",
        "parenthood",
        "vegetarianism",
    ],
}